create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char), ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) generated by default as identity, ds_email varchar2(255 char), ds_senha varchar2(255 char), nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char), ds_senha varchar2(255 char), nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char), ds_senha varchar2(255 char), nm_usuario varchar2(255 char), sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char), ds_senha varchar2(255 char), nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char) not null, primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char), ds_senha varchar2(255 char), nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char), nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario number(10,0) not null, ds_email varchar2(255 char) not null, ds_senha varchar2(255 char) not null, nm_usuario varchar2(255 char) not null, sb_usuario varchar2(255 char), primary key (id_usuario));
create table tb_usuario (id_usuario integer not null, ds_email varchar(255) not null, ds_senha varchar(255) not null, nm_usuario varchar(255) not null, sb_usuario varchar(255), primary key (id_usuario)) engine=InnoDB;
create table tb_usuario (id_usuario integer not null, ds_email varchar(255) not null, ds_senha varchar(255) not null, nm_usuario varchar(255) not null, sb_usuario varchar(255), primary key (id_usuario)) engine=InnoDB;
create table tb_usuario (id_usuario integer not null, ds_email varchar(255) not null, ds_senha varchar(255) not null, nm_usuario varchar(255) not null, sb_usuario varchar(255), primary key (id_usuario)) engine=InnoDB;
create table tb_usuario (id_usuario integer not null, ds_email varchar(255) not null, ds_senha varchar(255) not null, nm_usuario varchar(255) not null, sb_usuario varchar(255), primary key (id_usuario)) engine=InnoDB;
create table tb_usuario (id_usuario integer not null, ds_email varchar(255) not null, ds_senha varchar(255) not null, nm_usuario varchar(255) not null, sb_usuario varchar(255), primary key (id_usuario)) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;

    create table tb_usuario (
        id_usuario integer not null,
        ds_email varchar(255) not null,
        ds_senha varchar(255) not null,
        nm_usuario varchar(255) not null,
        sb_usuario varchar(255),
        primary key (id_usuario)
    ) engine=InnoDB;
