version: '3.8'

services:
  app:
    build: .
    container_name: wisetrip-login-api
    ports:
      - 8080:8080
    environment:
      spring.cloud.gcp.sql.database-name: wisetrip-db
      spring.cloud.gcp.sql.instance-connection-name: gcp-learn-459823:us-central1:wisetrip-database



    restart: never

