version: '3.8'

services:
  app:
    build: .
    container_name: wisetrip-login-api
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://82.25.71.199:3306/wisetrip-db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: wisetrip-suser 
      SPRING_DATASOURCE_PASSWORD: JTHYJz6F1SAQHT
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: never

